### PR TITLE
Added Angular Gmap Search box

### PR DESCRIPTION
**Pull request by sreevisakh**
I used 2 tabs for indentation please revert back if it vary from what we used previously
template field for search box was a mandatory  field.
added search event to move map and show a marker in the selected place for now.

### CODE REVIEW

**Comment by gugwad** [comment]
I dont think we need tpl in file search.tpl.html ? Let me know if we need this.

**Comment by gugwad** [comment]
Yeoman generated code had two spaces indentation. Lets follow it as standard.

**Comment by sreevisakh** [comment]
tpl is added in the name just for convention to identify that its a template file rather than normal html file. I saw that in an example used the same

**Comment by gugwad** [comment]
I got to know :-1:

**Comment by sreevisakh** [comment]
what is appVeyor?

**Comment by gugwad** [comment]
Inspiration is :+1:  but copy paste is not :-1:

**Comment by gugwad** [comment]
appVeyor is one more build condom ;-)

**Comment by sreevisakh** [comment]
super! that had holes I guess it failed.

**Comment by gugwad** [comment]
Roger that ! Merging it.

**Pull request merged**
